---
- name: Verify
  hosts: all

  tasks:
    - name: Install which
      become: true
      package:
        name: which
        state: present

    - name: Check whether exa is installed
      command: which exa
      environment:
        TERM: xterm
      register: EXA_INSTALLED
      changed_when: false

    - name: Check OS version
      command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: false

    - name: Make sure exa is installed
      debug:
        var: EXA_INSTALLED

    - name: Show OS version
      debug:
        var: OS_VERSION
