---
- name: Verify
  hosts: all

  tasks:
    - name: Install which
      package:
        name: which

    - name: Check whether exa installed
      command: which exa
      environment:
        TERM: xterm
      register: EXA_INSTALLED
      changed_when: false

    - debug:
        var: EXA_INSTALLED
